### ISSUE TITLE
 Please upgrade to a 2.7.x release that supports hmac

### ISSUE THREAD

**Issue by ppabc** [StackStorm/st2-docker#160] opened 2018-11-08 10:34 UTC
**Describe the problem**
st2 run ansible.command hosts=node2 module_name=p
...
id: 5be40bf37352f2019ee32aee
status: succeeded
parameters: 
  cwd: /opt/stackstorm/packs/ansible
  hosts: node2
  module_name: ping
result: 
  failed: false
  return_code: 0
  stderr: "/opt/stackstorm/virtualenvs/ansible/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
  utils.DeprecatedIn23,"
  stdout: "node2 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}"

**Versions**
 - Host OS: [e.g. Ubuntu 14.04.5]
 - docker: [e.g. 17.12.1-ce]
 - docker-compose: [e.g. 1.21.1]
 - stackstorm/stackstorm image: [e.g. v2.7.1]

**To Reproduce**
If necessary, please specify steps to reproduce the behavior.

**Comment by LindsayHill** [comment] 2018-11-12 18:17
Duplicate of https://github.com/StackStorm/st2-docker/issues/125

You may be interested in using our ST2 on K8s configurations. Those underlying containers are built on top of Xenial. See https://github.com/stackstorm/st2-dockerfiles

**Closed by LindsayHill** 2018-11-12 18:17 UTC
